version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: patents
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: patents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
